### ISSUE TITLE
Objects are not created with public access

### ISSUE THREAD

**Issue by mcous** [jameslnewell/satay#1]
Hey! Cool little tool you've got here!

I just tried it to deploy a simple little site, and while the "folders" created had the correct permissions set (public read), the objects themselves did not. I had to add `params: {ACL: 'public-read'}` to all my groups. Since this is a static website upload tool, this seems like a sensible default for `params`.

Happy to PR if this is something you'd like to do

**Comment by jameslnewell** [comment]
Sounds good. PRs welcome!
